# Set the auto-connect minimum interval time to be 7.5ms
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6

# 11.25ms The "time interval between deputy and master"
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9

# The delay is 0, which means that the deputy will not skip any link keys and always maintain an active listening state. It can solve the problem of being unable to be awakened by the master because he sleeps too deeply, and slightly increase the power consumption of the deputy
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# More than 4000 ms, no communication during this time period, the link will be disconnected
# CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=120

# Enable 32kHz crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

# Turn knob on
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# CONFIG_EC11_TRIGGER_OWN_THREAD=y 

# MOUSE
CONFIG_ZMK_POINTING=y

# CONFIG_ZMK_EXT_POWER=y

# Increase keyboard debuffing
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enable keyboard RGB function
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_LED_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# Sleep causes the left (slave) split kb to remain sleeping even when the right side is made awake
CONFIG_ZMK_IDLE_TIMEOUT=20000
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# Under this file, both sides of the split take effect, and the left and right conf files inside are operated when both sides have different functional configurations

# Bluetooth Enhancement
# CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=y
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Key change
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
